((nil . ((fill-column . 110)
         (eval . (setq projectile-find-dir-includes-top-level t))
         (eval . (setq-default indent-tabs-mode nil))
         (eval . (global-set-key [f5] 'sbt-command))
         )))
