# Use container-based infrastructure
sudo: required
dist: trusty

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - node_modules

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

scala:
  - 2.12.2

node_js:
  - "6.11.1"

jdk:
  - oraclejdk8

script:
  - cp conf/logback-test.xml.template conf/logback-test.xml
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage "testOnly -- -l PersistenceTest"
  - npm install
  - node_modules/karma/bin/karma start

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

branches:
  only:
  - master
  - development
